name: WorkingClocks
main: me.abcric.bukkit.workingclocks.WorkingClocks
version: 1.2
api-version: 1.13
author: ABCRic
permissions:
    WorkingClocks.use:
        description: Allows the user to use clocks to see the time
        default: true